version: "2"
services:
  sga:
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"